import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import StoreProvider from "./store/storeProvider";
import Logout from "./components/Logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("insdie layout")
  return (
    <html lang="en">
    
      <body
        className= "flex  w-full h-full"
      >
      <StoreProvider>
      <div className="h-full">
        <Sidebar/>
        </div>
        <div className="flex flex-col   overflow-y-scroll  w-full max-h-screen">
           <div className=" flex justify-end mx-20 mt-4">
            <Logout/>
           </div>
            
        {children}
        </div>
      
        </StoreProvider>
      </body>
    </html>
  );
}
